[package]
name = "ruut-functions"
author = "Ludovico Furlanetto"
description = "A math library that allows for parsing functions from string and perform integration, derivation and evaluation. Also supports functions with 2 and 3 variables"
license = "MIT"
version = "0.0.6"
edition = "2021"
